### ISSUE TITLE
'static site generator' kurulumu

### ISSUE THREAD

**Issue by muatik** [turkishtechforum/berlin-kilavuzu#2]
Jekyll gibi veya gitbook gibi bir sistem kurulumu yapip iceriklerin ziyaretcilerin gorebilecegi bicime getirilmesi gerekiyor. 

bkz: https://jekyllrb.com/

**Comment by muatik** [comment]
https://turkishtechforum.github.io/berlin-kilavuzu/

**Comment by koraybostanci** [comment]
alternatif olarak [mkdocs](https://www.mkdocs.org/) da kullanilabilir. hizlica soyle bir ornek birakiyorum.

![image](https://user-images.githubusercontent.com/8762343/76467318-a7162e80-63e9-11ea-8d6d-398a789b1ada.png)

**Comment by muatik** [comment]
Bence markdown destekleyen herhangi bir teknologi uygun.

html, css vs'ye bulasmadan markdown formatinda yazabilirsek daha cok ozellikle web teknolojilerini bilmeyenler de katki saglayabilir

**Comment by AbdullahG** [comment]
@koraybostanci abi ss'i localde mi aldın? sevdim o tool'u, bağlanıp incelesek birlikte?
@muatik

**Comment by koraybostanci** [comment]
aynen mkdocs’u download edip dummy içerik ekleyip lokal’de almıştım screenshot’ı. yine yaparız 5dk’da no problem :)

jykll da kullanılabilir github’da default geldiği için, güzel bi template bulabiliriz ona da. 

markdown only olsun gerisi çok önemli değil @muatik’in dediği gibi.

**Comment by koraybostanci** [comment]
Yine mkdocs ile farkli bir tema ile soyle bir sey de mumkun
![image](https://user-images.githubusercontent.com/8762343/77006795-5eb7bd00-6963-11ea-892f-c165fca76a11.png)

**Comment by metoikos** [comment]
Gatsby vs de olabilir ama son paylastigin material tema ekran guzel gorunuyor.

**Comment by koraybostanci** [comment]
konuştuğumuz gibi mkdocs-material template ile hızlı birşeyler yapıp repo’ya push edicem. Üzerine konuşuruz akabinde.

**Comment by koraybostanci** [comment]
> konuştuğumuz gibi mkdocs-material template ile hızlı birşeyler yapıp repo’ya push edicem. Üzerine konuşuruz akabinde.

https://turkishtechforum.github.io/berlin-kilavuzu/

**Comment by metoikos** [comment]
Cok guzel gorunuyor. Eline saglik. Ileride ihtiyac duyarsak degistirirz arayuzu. Su an bu yeterli gibi.
